baseURL = 'https://beta.ridewestside.org/'
languageCode = 'en-us'
title = 'Ride Westside'
theme = 'linkpage'

[params]
  description = "Building community through cycling"
  author = "Ride Westside"

  # Social media links
  [params.social]
    instagram = "https://instagram.com/ride_westside"
    facebook = "https://www.facebook.com/profile.php?id=100094262499529"
    bluesky = "https://bsky.app/profile/ridewestside.bsky.social"
    ridewithgps = "https://ridewithgps.com/organizations/14703-ride-westside/home"
    github = "https://github.com/ridewestside/website"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
